# mybatis plus 配置
mybatis-plus:
  mapper-locations: classpath:org/dromara/dynamictp/admin/modules/*/repository/mapper/*Mapper.xml
  typeAliasesPackage: org.dromara.dynamictp.admin.modules.**.domain.entity
  global-config:
    banner: false
    db-config:
      # 主键类型
      id-type: assign_id
      # 字段策略
      insert-strategy: not_null
      update-strategy: not_null
      table-underline: true
      logic-delete-field: is_deleted